
name: RELEASE

on:
  workflow_dispatch:
    inputs:
      bump:
        required: true
        description: "选择版本类型：latest, beta, next"
        default: "latest"

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --registry=https://registry.npmjs.org/

      - name: Build project
        run: pnpm run build

      - name: Authenticate with NPM Registry
        run: |
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish NPM
        run: npm publish --tag ${{ github.event.inputs.bump }}
